- name: Remove anonymous users
  command: |
    mysql -p{{ mysql_root_password }} -ne "{{ item }}"
  with_items:
  - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely | RedHat
  command: |
    mysql -p{{ mysql_root_password }} -ne "{{ item }}"
  with_items:
  - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it | RedHat
  command: |
    mysql -p{{ mysql_root_password }} -ne "{{ item }}"
  with_items:
  - DROP DATABASE IF EXISTS test
  - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: Reload privilege tables | RedHat
  command: |
    mysql -p{{ mysql_root_password }} -ne "{{ item }}"
  with_items:
  - FLUSH PRIVILEGES;
  changed_when: False
