---

- name: Installing Apache web server and upload our index.html
  hosts: myservers
  become: yes

  vars:

    source_content_folder: ./data
    destination_content_folder: /var/www/html

  tasks:

  - block:  ## Block for RadHat ##

    - name: Install Apache | RedHat
      dnf:
        pkg: httpd
        state: latest
        update_cache: yes

    - name: Start Apache | RedHat
      systemd:
        name: httpd
        enabled: yes
        masked: no
        state: started

    - name: Import REMI repository GPG key | RedHat
      rpm_key:
        key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
        state: present

    - name: Install REMI repository | RedHat
      dnf:
        name: https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
        state: present

    - name: Install a REMI module with php-8.1
      dnf:
        #name: '@php:7.4'
        name: '@php:remi-8.1'
        state: present

    - name: Install php-8.1 | RedHat
      dnf:
        pkg:
         - php
         - php-fpm
         - php-mysqlnd
         - php-cli
         - php-common
         - php-opcache
         - php-mbstring
         - php-gd
         - php-curl
        state: latest
        update_cache: yes

    - name: Start php-fpm | RedHat
      systemd:
        name: php-fpm
        enabled: yes
        masked: no
        state: started
      notify:
       - "Apache restart for Redhat"

    when: ansible_os_family == "RedHat"



  - block: ## Block for bullseye

    - name: Install tools | bullseye
      apt:
        pkg:
          - apt-transport-https
          - lsb-release
          - ca-certificates
          - curl
          - gnupg
        state: latest
        update_cache: yes

    - name: Import SURY repository php GPG key | bullseye
      apt_key:
        url: https://packages.sury.org/php/apt.gpg

    - name: Install SURY repository php | bullseye
      apt_repository:
        repo: deb https://packages.sury.org/php {{ ansible_distribution_release }} main

    when: ansible_distribution_release == "bullseye"



  - block: ## Block for Debian ##

    - name: Install Apache2 | Debian
      apt:
        pkg:
          - apache2
          - apache2-utils
        state: latest
        update_cache: yes

    - name: Start Apache | Denbian
      systemd:
        name: apache2
        enabled: yes
        masked: no
        state: started

    - name: Install php-8.1 | Debian
      apt:
        pkg:
         - php8.1
         - php8.1-fpm
         - libapache2-mod-php8.1
         - libapache2-mod-fcgid
         - php8.1-mysqlnd
         - php8.1-cli
         - php8.1-common
         - php8.1-opcache
         - php8.1-mbstring
         - php8.1-gd
         - php8.1-curl
        state: latest
        update_cache: yes

    - name: Start php8.1-fpm | Debian
      systemd:
        name: php8.1-fpm
        enabled: yes
        masked: no
        state: started
      notify:
      - "Apache restart for Debian"

    - name: Enable Apache modules for php8.1-fpm | Debian
      shell: |
        a2enmod proxy_fcgi setenvif && a2enconf php8.1-fpm
      notify:
      - "Apache restart for Debian"


    when: ansible_os_family == "Debian"


  - name: Copy content
    copy:
      src: "{{ source_content_folder }}/{{ item }}"
      dest: "{{ destination_content_folder }}/{{ item }}"
    with_items:
      - index.html
      - info.php

  - name: Copy content - template files
    template:
      src: "{{ item }}"
      dest: "{{ destination_content_folder }}/{{ item | basename | regex_replace('.j2','.html') }}"
    with_fileglob:
      - "{{ source_content_folder }}/*.j2"



  handlers:

    - name: Apache restart for Redhat
      systemd:
        name: httpd
        state: restarted

    - name: Apache restart for Debian
      systemd:
        name: apache2
        state: restarted
