---

- name: Installing LAMP and upload content files
  hosts: "{{ selected }}"
  become: yes
  #gather_facts: false

  roles:
    - role: lamp
      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"
